module.exports = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "api", // Généré par typedoc
        },
      ],
    },
  ],
};
